### ISSUE TITLE
Design an Icon

### ISSUE THREAD

**Issue by sw1pr0g** [F1st3K/EasyVPN#50]
We need a visually appealing and representative icon for the EasyVPN project. The icon should encapsulate the essence of the project — easy, secure, and reliable VPN management. The icon will be used in various places, such as the website, application UI, and documentation, so it should be versatile and recognizable.

**Objectives:**

 1. Simplicity and Clarity: The icon should be clean and simple, ensuring it is easily recognizable even at smaller sizes.
 2. VPN/connection representation: The design should hint that the tool is related to VPN and network connections.
 3. Modern and Professional: The icon should have a modern and professional look, in line with current design trends.
 4. Color scheme: Monochrome so that the color can be selected later.

**Technical Considerations:**

- Formats Required: Please provide the icon in vector format (e.g., SVG), along with PNG versions in various sizes (16x16, 32x32, 64x64, 128x128).
- Compatibility: Ensure the icon looks good on both light and dark backgrounds, or provide alternative color schemes if needed.
- Accessibility: The icon should be clear and distinguishable for users with visual impairments (consider testing or adhering to WCAG contrast guidelines).

**Comment by sw1pr0g** [comment]
@F1st3K any addings or suggestions?

**Comment by N1ck-N1ck** [comment]
this is what I can offer, you can check it out
![изображение_2024-08-21_225317189](https://github.com/user-attachments/assets/5fad3ad2-eb3c-4adc-82fa-fc4758dba6ad)

**Comment by F1st3K** [comment]
HI @N1ck-N1ck  thanks for the suggested options and the work done, but I would like the icon to be minimalistic, something like a circle and a couple of letters in the center and all this would be somehow interestingly designed according to the theme.

**Comment by F1st3K** [comment]
![EasyVPN-logo dark](https://github.com/user-attachments/assets/289afc05-c2a3-44e9-abc0-73416101ef02)
![EasyVPN-logo light](https://github.com/user-attachments/assets/912ce819-2ea1-49ae-aeb2-b0af7f0a987b)
![EasyVPN-logo](https://github.com/user-attachments/assets/20dc1d16-a7d2-4cca-bf96-f23a886c55cb)
![photo_2024-10-12_16-20-34](https://github.com/user-attachments/assets/c902c6ab-5c32-43b7-be8a-a9fde0fde24d)
